export default [
  {
    title: 'Home',
    to: { name: 'root' },
    icon: { icon: 'tabler-smart-home' },
    action: 'read',
    subject: 'branch',
  },
  {
    title: 'clients.title',
    to: { name: 'customers' },
    icon: { icon: 'tabler-users' },
    action: 'read',
    subject: 'branch',
  },
  {
    title: 'settings',
    to: { name: 'employees' },
    icon: { icon: 'tabler-user-cog' },
    action: 'read',
    subject: 'admin',
  },
  {
    title: 'requests.title',
    to: { name: 'requests' },
    icon: { icon: 'tabler-sort-descending' },
    action: 'read',
    subject: 'branch',
  },
  {
    title: 'certificates.title',
    to: { name: 'certificates' },
    icon: { icon: 'tabler-file-certificate' },
    action: 'read',
    subject: 'operator',
  },
  {
    title: 'tokenModule.title',
    to: { name: 'tokens' },
    icon: { icon: 'tabler-device-usb' },
    action: 'read',
    subject: 'branch',
  },
  {
    title: 'reports.title',
    to: { name: 'reports' },
    icon: { icon: 'tabler-chart-bar' },
    action: 'read',
    subject: 'admin',
  },
  {
    title: 'logs.title',
    to: { name: 'logs' },
    icon: { icon: 'tabler-file-text' },
    action: 'read',
    subject: 'admin',
  },
]
